### ISSUE TITLE
Navigating to a parameterized route with siblings(viewports) results in an error.

### ISSUE THREAD

**Issue by jon123** [aurelia/router#314] opened 2016-03-28 05:17 UTC
Referring to the use of viewports/siblings found in this closed issue:

https://github.com/aurelia/router/issues/56

Creating sibling with a parameterized route (as shown below) results in an error when navigating to the route.

```
{
route:':id/route',
  viewPorts = {
    'left-side': {
      moduleId: 'some-module;
    },
    'right-side':{
      moduleId:'another-module'
    }
  }
}
```

Navigating results in the following error: `aurelia-bundle.js:8297ERROR [app-router] Error: Invalid Route Config: Configuration for viewPort "default" was not found for route: ":id/route."(…)`

The router is looking for a 'default' entry in the viewPorts array.

Here is a plunker to illustrate the problem.  

http://plnkr.co/edit/2MReXyfgUlTz75lJSS6I?p=preview

**Comment by jon123** [comment] 2016-03-28 07:22
Should be noted that this error only occurs when navigating in-app.  The error occurs via an href within the app such as `#/someChildRoute/someId/route`. Pasting a url such as `localhost:9000/#/someChildRoute/someId/route` into a new browser window and loading the app does not invoke the error and appears to work as expected.

**Comment by nexbit** [comment] 2016-04-16 15:22
Hi, it works with the following fix:

```
    config.map([
      { route: '',  name: 'child-route',     moduleId: 'no-selection', title: 'Welcome' },
      { route:':id/main-content', name:'main-content-viewport', 
          viewPorts: {
          /* the router is looking for an entry named  'default' defined here-in */
                'tabs'          : { moduleId: './tabs'},
                'main-content'  : { moduleId:'./main-content'},
                default: { moduleId:'./main-content'}
          }
      }
    ]);
```

I don't know if it's the intended behaviour, but it works the same even for a root router.
In my app I follow I guideline where I mark secondary viewports with an explicit name (like `tabs` in your example) and I leave the main content anonymous (router-view without a name).
Then in my router config I associate the `default` viewport to the main module, and that will be rendered in the anonymous router-view element.

If you are satisfied with the workaround, someone from the core team can close this issue.
P.

**Comment by jon123** [comment] 2016-04-17 19:10
I tried the 'default' entry and it works acceptably.  

What concerns me is the full page reload does not require 'default' . In theory, an internal href navigation should not give a different result than a full page reload using the same url.  This sniffs of a potential problem.

For me the use of 'default' is acceptable but perhaps is not the most desirable long term solution.  Apart from being semantically non-descriptive, 'default' anchors the order of elements when multiple `router-view` are used in the same view.  In some edge-cases the ordering of siblings cannot be nicely/easily achieved..   

An example is as follows where the goal is to swap order of siblings depending on the route

```
//route 1 - initial order in someChildRouter.html
<router-view name="A"></router-view>
<router-view name="B"></router-view>
<router-view name="default"></router-view> //display main content for A
``` 

```
//route 2 - would not be possible to achieve reusing someChildRouter.html
<router-view name="A"></router-view>
<router-view name="default"></router-view>  //display main content for B
<router-view name="B"></router-view>
``` 

Without 'default' the following would work (the unused router-view is ignored).
```
<router-view name="A"></router-view>
<router-view name="main-content-B"></router-view>
<router-view name="B"></router-view>
<router-view name="main-content-A"></router-view>
```

**Comment by Alexander-Taran** [comment] 2018-02-28 11:08
There have been changes to router design. It is now possible to have null as module for view-port..
I forked you repro and modified it in a way to allow for your scenario
http://plnkr.co/edit/rFZIh0iC0E30r7y4yqfc?p=preview

main difference is in configuration of child router

```
  configureRouter(config: RouterConfiguration, router: Router) {
    config.map([
      { route: '',  name: 'child-route',       viewPorts: {
                'main-content'  : { moduleId:'./no-selection'}
               
          }, title: 'Welcome' },
      { route:':id/main-content', name:'main-content-viewport',
          viewPorts: {
          /* the router is looking for an entry named  'default' defined here-in */
                'tabs'          : { moduleId: './tabs'},
                'main-content'  : { moduleId:'./main-content'},
               
          }
      },
     
    ]);
```

I also removed default `<router-view>` from the corresponding view


here is the relevant documentation
http://aurelia.io/docs/routing/configuration#rendering-view-ports

and the blog post about this release
http://aurelia.io/blog/2018/01/22/big-changes-in-the-aurelia-router-150-release

**Comment by Alexander-Taran** [comment] 2018-02-28 11:08
can be closed

**Comment by davismj** [comment] 2018-02-28 13:06
@jon123 

@Alexander-Taran is right. You wouldn't want to have the `<router-view>` in child-router.js without defining view port configurations for the `'default'` view port.

**Closed by davismj** 2018-02-28 13:06 UTC
Labels: bug
