### ISSUE TITLE
The first page (module) in a router cannot have a child router.

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [aurelia/router#124] opened 2015-06-11 06:45 UTC
Motivation: Two pane apps such like iPad apps have the top nav-bar, the master pane and the detail pane. The master pain has a child router in order to show detail info in the detail pane.

Phenomenon: If the URL of the first page in a router is '' and the page has its own child router, links governed in the child router in the first page point to the pages in the parent router, not in the child router.

These do not work as expected. All links in the child-router.html jump via the top nav-bar.
This might not a bug. But explanation is needed in the documentation.

```
    config.map([
      { route: '',  moduleId: './child-router',      nav: true, title:'child-router' },

    config.map([
      { route: ['', 'child-router'],  moduleId: './child-router',      nav: true, title:'child-router' },

    config.map([
      { route: ['child-router', ''],  moduleId: './child-router',      nav: true, title:'child-router' },
```
Workaround:

```
    config.map([
      { route: 'child-router',  moduleId: './child-router',      nav: true, title:'child-router' },
      { route: '',  moduleId: './child-router',      nav:false, title:'child-router' },
```

**Comment by bryanrsmith** [comment] 2015-06-11 14:36
This sounds like a duplicate of #27, which we do plan on fixing. Does that issue sound like it covers the problem you're experiencing?

**Comment by bryanrsmith** [comment] 2015-06-23 05:45
I'm going to go ahead and close this one since I think it's a duplicate. Please let me know if I'm mistaken and I will reopen it.

**Closed by bryanrsmith** 2015-06-23 05:45 UTC

**Comment by HIRANO-Satoshi** [comment] 2015-06-23 05:55
No problem, maybe. Thank.
