### ISSUE TITLE
Route Not found when using child routers

### ISSUE THREAD

**Issue by shajiuk** [aurelia/router#254] opened 2015-11-24 10:19 UTC
I have a child-router defining routes in a file called index.js. Then in the following app.js file I reference the index.js file as follows. The index.html files loops through the navigation and constructs the menu items correctly with the routes correct in the href part.

The problem I am having is that it cannot find the routes. Any ideas?

If I put the routes in the app.js file it finds it.

app.js

import 'bootstrap';
import 'bootstrap/css/bootstrap.css!';
import {inject, bindable} from 'aurelia-framework';
import {RatesHandler} from './ratesHandler';

@inject(RatesHandler)
export class App {

constructor(ratesHandler) {
    this.ratesHandler = ratesHandler;
}
configureRouter(config, router) {
    this.router = router;

    config.title = 'Rates';
    config.map([
        { route: ['', 'index'], moduleId: './index', name: 'index', nav: false, title: 'Rates' },
        { route: 'rates/:id', moduleId: './index', title: 'Rates' }
    ]);
}
}

Index.js

import {inject, bindable} from 'aurelia-framework';
import {RatesAPI} from './ratesAPI';
import {Dispatcher, handle} from 'aurelia-flux';

@inject(RatesAPI, Dispatcher)
export class Index{

title = 'Rates';

constructor(ratesApi, dispatcher){
    this.ratesApi = ratesApi;
    this.dispatcher = dispatcher;
}

activate(params, routeConfig) {
    this.dispatcher.dispatch('rates.get', params.id);
}

configureRouter(config, router){
    config.map([
      { route: ['','contract-rate'],  moduleId: './contract-rate/contract-rate', title:'Contract Rate', nav: true },
      { route: 'supplement-rate',  moduleId: './supplement-rate/supplement-rate', title:'Supplement Rate', nav: true },
      { route: 'opaque-rate',  moduleId: './opaque-rate/opaque-rate', title:'Opaque Rate', nav: true },
      { route: 'discounted-rate',  moduleId: './discounted-rate/discounted-rate', title:'Discounted Rate', nav: true },
      { route: 'early-bird-rate',  moduleId: './early-bird-rate/early-bird-rate', title:'Early Bird Rate', nav: true },
      { route: 'rolling-advance-rate',  moduleId: './rolling-advance-rate/rolling-advance-rate', title:'Rolling Advance Rate', nav: true },
      { route: 'advance-rate',  moduleId: './advance-rate/advance-rate', title:'Advance Rate', nav: true },
      { route: 'report',  moduleId: './report/report', title:'Report', nav: true }
    ]);

    this.indexRoutes = router;
// I tried: this.router = route

}
}

index.html

    <form role="form" submit.delegate="update()" class="form-group">
        <ul class="nav nav-tabs">
            <li role="presentation" repeat.for="row of indexRoutes.navigation" class="${row.isActive ? 'active' : ''}">
                <a href="${row.href}">${row.title}</a>
            </li>
        </ul>

    </form>

    <router-view router.bind="rates"></router-view>
</section>

**Comment by npelletm** [comment] 2015-11-26 10:37
Same issue.

It seems that the baseUrl router property is populated too "late".
With a hack 
```router.baseUrl = "parentRoute"
```

**Comment by shajiuk** [comment] 2015-11-26 13:16
Thanks for the reply but I don't get what you mean - sorry. 

What is the parentRoute? The main page has a header and footer from a microservice and that sets the baseURL. Then within this page is a section where the the above page gets loaded. The page has a series of tabs as defined in the code (Supplement rate, Opaque Rate,....) above and defined in index.js  The tabs get genereted with the correct href but when you click on it it does not navigate.

So can you tell me where I set the baseURL to get this working please? With my code amended will really help. Much appreciated.

**Comment by npelletm** [comment] 2015-11-26 21:34
Sorry, perhaps it is not the same use case...
In my case i have a parent router with a parent route : "/parentRoute" ("/index" in your case ) and in the child router when configureRouter function called, a route not found error is raised because it seems that child router navigate too early. 
With the baseUrl hack route not found error disappear.
In addition, this error appears only on the first child router navigation.

This related [bug](https://github.com/aurelia/framework/issues/247) could help.
This [bug](https://github.com/aurelia/router/issues/185) could help with a potential workaround

**Comment by nomack84** [comment] 2015-12-01 22:33
@shajiuk This seems to be a duplicate of #27. Try this:

```javascript
config.map([
    { route: 'index', moduleId: './index', name: 'index', nav: false, title: 'Rates' },
    { route: 'rates/:id', moduleId: './index', title: 'Rates' },
    { route: '', redirect: 'index' }
]);
```
Unfortunately you cannot use child routes with empty urls yet.

**Comment by TravcoUser** [comment] 2015-12-02 11:45
Thanks guys for your help on this.
@nomack84 - this seems to work - but intermittently! It must be something in my end.

**Comment by shajiuk** [comment] 2015-12-02 11:49
Thanks for your help guys.
@nomack84  - your solution seems to work but intermittently! It's probably is something at my end.

**Comment by nomack84** [comment] 2015-12-02 15:40
Yeah, child routers has some bugs that aren't solved yet.

**Comment by Jenselme** [comment] 2015-12-19 22:28
I have the same problem. The solution of @npelletm worked for me.

**Comment by npelletm** [comment] 2015-12-20 00:08
Thanks for my "solution" but it's more a workaround or a dirty hack....

**Comment by EisenbergEffect** [comment] 2016-05-16 13:39
We recommend using redirect from the empty route to a named route to solve this issue.

**Closed by EisenbergEffect** 2016-05-16 13:39 UTC
