### ISSUE TITLE
Router navigate twice

### ISSUE THREAD

**Issue by hadrienl** [aurelia/router#322] opened 2016-04-06 16:01 UTC
Since I upgraded to beta 1.2 I have a strange behavior : when I navigate in my app, all of my views are loaded twice. If I set some `console` in `activate` method of controlleurs, I can see it two times. If I observe `router.currentInstruction`, event is fired twice :

![capture d ecran 2016-04-06 17 56 34](https://cloud.githubusercontent.com/assets/225382/14323623/83e7580a-fc21-11e5-96b6-87004c0af538.png)

**Comment by hadrienl** [comment] 2016-04-07 07:44
It's hard to reproduce. I'm having the problem when loading a view with a child router. If I load the root view first, then, the rooter will works fine when I navigate child routes. Then, If I reload from a child route, I'll get the twice load.

**Comment by hadrienl** [comment] 2016-04-07 08:05
App.js have this configuration:

```
config.map([{
      route: '/',
      name: 'home',
      moduleId: 'home/home'
    }, {
      route: 'login',
      name: 'login',
      moduleId: 'auth/login'
    }, {
      route: 'su',
      name: 'Super User',
      moduleId: 'su/su'
    }, {
      route: 'profile/:provider/:name',
      name: 'profile',
      moduleId: 'profile/profile'
    }]);
```

If I load my app on /, /su or /login, I'll get the double navigation but not on /profile/foo/bar. Then, if I replace `route: 'profile/:provider/:name',` for `route: 'profile',`, I'll get the bug too.

**Comment by EisenbergEffect** [comment] 2016-04-26 11:49
Can you re-create this on the nav skeleton for us and attach the src? I haven't seen this behavior with similar setups.

**Comment by EisenbergEffect** [comment] 2016-07-05 18:27
Closing since cannot reproduce and no repro from OP.

**Closed by EisenbergEffect** 2016-07-05 18:27 UTC
