### ISSUE TITLE
CurrentInstruction property on non-Chrome browser doesn't exist on startup

### ISSUE THREAD

**Issue by AStoker** [aurelia/router#226] opened 2015-10-16 15:46 UTC
I have my route configuration inside of an `app.js` file. Inside the app class, I have a configureRouter function which is set up like this:
``` javascript
    configureRouter(config, router) {
        config.title = 'Central';
        config.addPipelineStep('authorize', NavigationChange);
        config.map([
            { 	
                route: [''],          
                name: 'Central',      
                title: 'Central',              
                viewPorts: {
                    'central-nav': 	{moduleId: 'central'},
                    'sub-nav': 		{moduleId: 'empty'},
                    'view-space': 	{moduleId: 'viewspace'}
                },     
                nav: false,
                settings: {icon: 'fa-home',app: "Flow",activeViewPort: 'central-nav'}	
            },	        
	        { 	
	            route: ['inbox', 'inbox/:packageId', 'inbox/:packageId/:packageItemId'],          
	            name: 'Inbox',      
	            title: 'Inbox',              
	            viewPorts: {
	                'central-nav': 	{moduleId: 'central'},
	                'sub-nav':      {moduleId: 'flow/inbox'},
	                'view-space': 	{moduleId: 'viewspace'}
	            },     
	            nav: true,
	            settings: {icon: 'fa-inbox',app: "Flow",activeViewPort: 'sub-nav'}            
	        }
        ]);
      console.log(this.router.currentInstruction); //Safari/IE -> undefined
      //Logic for listening to this.router.currentInstruction (http://blog.durandal.io/2015/04/03/aurelia-adaptive-binding/)
      //This causes chaos 
      var subscription = this.multiObserver.observe([
         this.router, 'currentInstruction']
      ], () => this.routerChange());
    }
```
This works fine in Chrome, as the `currentInstruction` property exists right off the bat here. However, in Safari, and IE, the property doesn't exist until later, and therefore I can't get the observer to listen properly.  

The bug seems to be the timing of `currentInstruction` property being created.

**Comment by AStoker** [comment] 2015-10-16 15:55
Not sure if this is entirely related to the router. It seems that by bringing things into the app's constructor differently (either through injection or 'new'ing up an object) I get different results.  
The odd ball is the MultiObserver class I'm trying to bring in. Would using `@inject` over sewing up an exported class cause differences?

**Comment by bryanrsmith** [comment] 2015-10-27 05:02
@EisenbergEffect @jdanyow Any idea on this one?

**Comment by EisenbergEffect** [comment] 2015-10-27 05:02
Can it be reproduced?

**Comment by AStoker** [comment] 2015-10-27 12:41
It's possible that I'm doing something funky. What I did to reproduce this was take the skeleton project which imported a module titled MultiObserver (based off of http://blog.durandal.io/2015/04/03/aurelia-adaptive-binding/), and then inject it and set the property in the constructor. That may be way off base, but it seems that when I do that, I get the issue to crop up...

**Comment by bryanrsmith** [comment] 2015-10-28 05:00
`currentInstruction` isn't set until the first navigation completes. I'd expect it to always be `undefined` in your app's `configureRouter` method. I don't know the observer stuff very well myself, but I'd be happy to help debug if you can provide a plunker or repo for me to check out. Otherwise maybe Rob has an idea.

**Comment by bryanrsmith** [comment] 2016-02-13 04:35
I'm going to close this for now since we have other issues to track the problem with late CurrentInstruction assignment.

**Closed by bryanrsmith** 2016-02-13 04:35 UTC
Labels: bug, help wanted, question
