### ISSUE TITLE
Navigation pipeline should support cancelation

### ISSUE THREAD

**Issue by devteamexpress** [aurelia/router#217] opened 2015-09-27 14:16 UTC
one of my viewmodels activate function takes a while to complete around 15 seconds, if the route is mid activation and then I click another route, the router will wait for the old one to finish activating before proceeding to the new one which means that you're essentially stuck for those 15 seconds. Is there a way for it to cancel the old activation and proceed to the new one.

**Comment by EisenbergEffect** [comment] 2015-09-27 14:20
There is no notion of "cancellation" in promises at this point in time, though I have heard talk that the API may be improved to include that at some point in the feature. But, as things are, there's nothing that Aurelia can really do to handle this automatically.

My recommendation would be, for this case, to not return a promise from your activate method. Instead, fix up the view for that screen so that it shows its own internal loading indicator until the data is loaded. That way the router is free to navigate away even if the data hasn't completed loading.

**Comment by devteamexpress** [comment] 2015-09-27 14:28
Is their a way that Aurelia that if given a promise can wrap that promise in another container which can allow for an early reject. So let's say PromiseWrapper would take a promise and have a method called EarlyReject which would reject the promise mid way.

**Comment by bryanrsmith** [comment] 2015-09-27 18:19
I'm going to leave this open because I think we do need to handle cancelation at some point, and we don't have an issue tracking it yet.

**Comment by mttmccb** [comment] 2017-01-29 06:39
While not part of promises bluebird has cancellation http://bluebirdjs.com/docs/api/cancellation.html

**Comment by Alexander-Taran** [comment] 2018-03-12 01:41
Thou shalt not force the user to wait 15 seconds for activate to finish.
Long running loads should have their own spinners in the view.

I'd close this

**Comment by EisenbergEffect** [comment] 2018-03-12 02:04
Let's keep it for now, though I don't think we'd do it outside of overhauling the router in some future version.

**Comment by fkleuver** [comment] 2018-03-12 02:27
With regards to overhauling the router in a future version, I'm adding a reference to a [somewhat related issue](https://github.com/aurelia/templating-router/issues/26). It's about rendering a parent route's viewmodel before a child route's `activate` promise has resolved.

**Comment by Alexander-Taran** [comment] 2018-03-12 08:29
Might I add that whole middleware pipeline as in asp.net core and koa looks so appealing

**Comment by davismj** [comment] 2018-03-15 06:19
I'm honestly with Alex here. If you want to support cancellation, you can easily do this by wrapping a promise.

```
activate() {
  return new Promise((resolve, reject) => {
    this.doMyReallyLongTimeThing().then(resolve);
    setTimeout(reject, 15000);
  }
}
```

@EisenbergEffect I'd vote to close. Your thoughts?

**Closed** 2018-03-15 06:23 UTC
Labels: enhancement

**Comment by evanlarsen** [comment] 2018-09-21 20:34
Cancelling the promise on the activate really doesn't solve @devteamexpress' issue.  The issue is that when a user is trying to navigate while the current page is still activating the router does not have the ability to cancel navigation and serve the new request. Instead it waits until the activate completes before navigating again.

Rejecting the activate on a page after 15seconds is not the desired effect. What is needed is a way to tell the router to stop its current processing and instantly route to another page.
