### ISSUE TITLE
Back button is broken in iOS since 1.5.0

### ISSUE THREAD

**Issue by powerbuoy** [aurelia/router#574] opened 2018-01-25 17:00 UTC
Since the latest update that introduced the very useful `isNavigating*` flags the back button is broken in iOS and seems to always take the user back to the home page.

To reproduce simply set up an Aurelia CLI app with at least 3 routes, then navigate from home, to route 2 to route 3 then hit the back button and you'll end up on home - not route 2.

**Comment by davismj** [comment] 2018-01-26 08:39
Thanks for bringing this to my attention. I'll take a look when I can get my hands on an iOS device.

Any idea what might be going on?

**Comment by powerbuoy** [comment] 2018-01-26 09:43
Unfortunately no :/ But after further testing it does seem like the back button _always_ brings you back to the home page for some reason. 

`window.history.length` seems correct (there's more than one entry in there at least) but `window.history.go(-1)` always takes you to the home page...

Same issue in the iOS simulator if you have access to an OSX machine.

**Comment by powerbuoy** [comment] 2018-01-26 09:48
If there's anything I can help you test just let me know and I'll do my best!

**Comment by davismj** [comment] 2018-01-26 09:58
I've got an old iPod touchy for testing, but I gotta get a charger for it lol. Appreciate the leads.

**Comment by powerbuoy** [comment] 2018-01-26 10:33
Lol OK :) I guess in the meantime I'll roll back a version.

**Comment by powerbuoy** [comment] 2018-01-26 11:11
Can confirm it's definitely a problem with `aurelia-router@1.5.0` - rolling back to `1.4.0` solves the issue.

**Comment by jwx** [comment] 2018-01-26 23:29
Could it have something to do with routes not being added to browser history? 

I don't think anything I've added has caused this (but yeah, if I had a nickel for every time...) but I have to admit I haven't tested my PRs on iOS on account of not having it available. :blush:

**Comment by jwx** [comment] 2018-01-26 23:30
(That blush looked way too happy. It's supposed to be a sad and embarassed blush, guys.)

**Comment by jerep** [comment] 2018-01-31 13:02
I have the exact same issue with Safari on Mac and downgrading to `aurelia-router@1.4.0` solved it.

**Comment by huochunpeng** [comment] 2018-02-05 03:34
I also encountered this problem on macOS Safari. You don't need an iOS device to debug.

**Comment by jimwards17** [comment] 2018-02-05 15:01
Possibly a related issue? 

https://github.com/aurelia/router/issues/528

I ran into both at the same time? Can anyone determine if downgrading the router to v1.4 fixes issue 528 as well?

**Comment by powerbuoy** [comment] 2018-02-05 15:05
@jimwards17 #528 was reported before 1.5.0 released afaik.

**Comment by powerbuoy** [comment] 2018-02-07 02:48
So... not to be that guy, but is anyone working on this? It's a pretty huge bug that's currently live and out there in the latest release of `aurelia-router`...

**Comment by davismj** [comment] 2018-02-07 09:20
All right so I got my touchy charged up and create a test repo: http://davismj.me/test-router/

I navigate Welcome > Github Users > Child Router. I click the back button. I'm at Github Users. This is the expected behavior.

I'll need a repro to move forward, @powerbuoy .

**Comment by powerbuoy** [comment] 2018-02-07 11:05
@davismj Cheers :) My guess is it doesn't affect hashChange apps because your example works in Safari for me. Here's a newly created Aurelia CLI app that exhibits the bug though.

[route-test.zip](https://github.com/aurelia/router/files/1702775/route-test.zip)

And here's a video: https://youtu.be/p-BHoAm6qNo

**Comment by huochunpeng** [comment] 2018-02-07 11:48
@davismj 
1. test on a Mac Safari should be easier for you.
2. I confirmed @powerbuoy's finding, you need to turn on pushState in router.`config.options.pushState = true;`.
3. in addition, you need `<base href="/">` in index.html, and set `config.options.root = "/";`, in order to reproduce the issue. Anyway, they are mandatory steps to turn on pushState, based on aurelia-router official document.

**Comment by davismj** [comment] 2018-02-07 12:37
Got it, so it is a push state issue. I'll take another look.

@huochunpeng no access to a mac sadly

I personally never use pushState in apps. Is it that popular of an option?

**Comment by huochunpeng** [comment] 2018-02-07 12:48
@davismj, to be honest, you might be the only one left using hash instead of push. :-)

**Comment by davismj** [comment] 2018-02-07 12:57
@huochunpeng are there any errors logged to the console in safari? that would be a huge help to me

**Comment by huochunpeng** [comment] 2018-02-07 13:04
@davismj I will check tomorrow once I got to office.

**Comment by powerbuoy** [comment] 2018-02-07 14:06
There are no errors in the Safari console. `window.history` looks like this:

![screen shot 2018-02-07 at 15 05 44](https://user-images.githubusercontent.com/1027780/35920542-6e5ea502-0c18-11e8-8480-84be6fbe08ca.png)

if that helps at all.

**Comment by mattgaspar** [comment] 2018-02-07 19:30
This bug **does** occur when using hash change.
I noticed that back actually removes the hash from the url.  Normally a link to a route of '' would normal change the browser address to /#/, but when pressing back the url changes to /

I heard mention on github of a feature that would prevent the back navigation from browsing to a previous site (different host).  Did that get implemented in 1.5?

@davismj - I was going to take a look at the router code but could figure out why there are type definitions in the .js files.  VS Code shows syntax errors all over!  Is there an extension to make this work?  Is there a document on the IDE setup for contributing to Aurelia?  I couldn't find anything.

**Comment by huochunpeng** [comment] 2018-02-07 22:00
@davismj zero error in Safari console for me too. Even with developmentLogging turned on, no extra debug/log/warn/error.

**Comment by davismj** [comment] 2018-02-08 05:15
Appreciate the feedback guys. I'll do what I can.

@mattgaspar Thanks for the insight, both on the bug and on contributing. I use sublime text and so I've never seen errors and never thought twice about it. I'll take another look and maybe look at adding documentation about contributing. In the mean time, check out the [flow types plugin for vs code](https://github.com/flowtype/flow-for-vscode). 

The typings exist for the generation for .dts files. They are technically TypeScript typings but when we build the JavaScript we use Babel and the flow plugin.

**Comment by huochunpeng** [comment] 2018-02-09 04:30
@davismj I confirm the issue come from https://github.com/aurelia/router/blob/c1720c4fc911f58fb9233ae88f182f2256a19d67/src/app-router.js#L143

Once you comment out that line, on more issue on Safari. It looks like Safari is not happy if you touch history state object.

**Comment by huochunpeng** [comment] 2018-02-09 05:01
Based on what I read from https://www.w3.org/TR/html50/browsers.html#history
```
7. Set history.state to a structured clone of cloned data.
```
Both `history.pushState` and `history.replaceState` need to CLONE the input state object.

Although the standard does not explicitly reject you from touching the cloned object, but to me it's common sense that the standard tries to protect the state object as immutable.

In this sense, Safari looks like the only browser strictly follow the standard.

@davismi it sounds likes Aurelia team need to revert `getState/setState` in aurelia-history 1.1.0, and find another way to implement the new router flags `isNavigatingForward/Back/...`.

**Comment by davismj** [comment] 2018-02-09 06:33
@huochunpeng Thanks for this, great info and saved me a lot of headache since I don't have a Safari machine.

I think `getState` and `setState` are still likely viable strategies, but my guess is that there is a problem in the implementation. If you were not able to modify the state variables at all, then the state variables are totally useless. If you are able to modify them, then it seems we're just doing it in a way that safari doesn't like and we just need to fix that.

My guess is that the problem is here. I think maybe Safari doesn't like not having a title in the `replaceState` method.
https://github.com/aurelia/history-browser/blob/master/src/index.js#L192

I'm reaching out to you on Gitter now. For additional info.

**Comment by davismj** [comment] 2018-02-09 09:53
@huochunpeng and I are working on it. I'll keep everyone posted here.

**Comment by jwx** [comment] 2018-02-09 10:14
@davismj @huochunpeng Might be that url is null, possibly similar to this: https://stackoverflow.com/questions/47145052/ios-11-1-securityerror-dom-exception-18-blocked-attempt-to-use-history-replac

**Comment by davismj** [comment] 2018-02-09 10:22
Unlikely, the third parameter is optional.

**Comment by jwx** [comment] 2018-02-09 10:35
I think we're already in the realm of Unlikely since such a fairly simple thing is not working. But technically, the third parameter isn't left out; it's set to `null`. And that might make a difference in Safari/iOS. Even though it's a bit ... unlikely.

**Comment by davismj** [comment] 2018-02-09 14:40
@huochunpeng https://github.com/aurelia/router/issues/574#issuecomment-364335789

Seems like Safari isn't strictly following the standard after all. Thanks again for debugging and finding the fix.

**Comment by huochunpeng** [comment] 2018-02-09 14:46
:-)

**Comment by powerbuoy** [comment] 2018-02-09 16:30
Awesome work guys!

**Comment by powerbuoy** [comment] 2018-02-14 15:59
Any ETA on a 1.5.1 release with this fix? :) The biggest use-case for me with `isNavigatingBack` is being able to restore the scroll position when the user goes back. We have a list of search results and it's not great UX to end up at the top of the list every time the user goes back to it.

**Comment by EisenbergEffect** [comment] 2018-02-14 16:32
@davismj Let me know when you're ready for me to do a new release.

**Comment by pndewit** [comment] 2018-02-20 13:27
I can confirm that [the PR](https://github.com/aurelia/history-browser/pull/35) fixes my issues, with navigating back on Safari in macOS, as well. Looking forward to this being merged and released!

**Comment by davismj** [comment] 2018-02-20 14:25
@EisenbergEffect can be pulled in, see PR comments

**Comment by powerbuoy** [comment] 2018-02-23 13:29
Any chance we'll see a release this week?

**Comment by EisenbergEffect** [comment] 2018-02-23 18:26
Yes. @davismj Can you go ahead and merge this? After that, just give me the all clear for a release and it will go out this weekend.

**Comment by pndewit** [comment] 2018-02-23 19:18
@EisenbergEffect, @davismj already merged the PR :)

**Comment by EisenbergEffect** [comment] 2018-02-24 00:56
LOL That's what I get for being in a rush! We'll get it out this weekend.

**Comment by davismj** [comment] 2018-02-24 06:51
https://github.com/aurelia/history-browser/releases/tag/1.1.1

**Closed** 2018-02-24 06:50 UTC

**Comment by powerbuoy** [comment] 2018-05-04 16:29
@jimwards17 care to elaborate?

**Comment by jimwards17** [comment] 2018-05-04 16:34
https://github.com/aurelia/history-browser/issues/40

**Comment by davismj** [comment] 2018-05-12 06:37
@jimwards17 that is a known issue: https://github.com/aurelia/router/issues/45
