### ISSUE TITLE
Router CurrentInstruction is null in 1.2.0

### ISSUE THREAD

**Issue by allencoded** [aurelia/router#472] opened 2017-02-22 17:32 UTC
Updated aurelia router to the latest 1.2.0 version and it seems to have a bug that isn't in the earlier versions.

` this.router.currentInstruction.getAllInstructions();`

Error
`Cannot read property 'getAllInstructions' of null`

Upon inspection router.currentInstruction is now null and I can't perform getAllInstructions() any longer due to that.

**Comment by EisenbergEffect** [comment] 2017-02-24 07:04
When/Where are you calling that api from?

**Comment by allencoded** [comment] 2017-02-27 15:57
I have a Breadcrumb class. Which currently works under aurelia router 1.1.1. Once navigation is successful it then calls the api endpoint:
this.router.currentInstruction.getAllInstructions(). 

In my attached:
```
this.subscription = this.ea.subscribe(
      'router:navigation:success',
      ::this.navigationSuccess);
```
```
navigationSuccess() {
    this.routes = this.router.currentInstruction.getAllInstructions();
}
```

At this point it is null only when I am using the latest version of the aurelia-router 1.2.0. Like I said though in my current 1.1.1 version it works well. 

I had copied Jeremy Danyow's response from here a long time ago when I first implemented this and our code is basically a direct mimic:
http://stackoverflow.com/questions/33689554/identify-the-current-route-in-aurelia

**Comment by RichiCoder1** [comment] 2017-02-27 17:48
@allencoded A temporary work around for this, if you haven't already found one, would be:
```
navigationSuccess(eventArgs) {
    const { instruction } = eventArgs;
    this.routes = instruction.getAllInstructions();
}
```
*should* work

**Comment by EisenbergEffect** [comment] 2017-02-27 18:19
I think we must have made a bug fix that caused a regression here. Is anyone interested in submitting a PR to fix the issue. I can make a quick turnaround on the release.

**Comment by jagonalez** [comment] 2017-04-19 06:00
@allencoded I'm not able to reproduce this error. Are you able to share a gist with code that creates the error?

**Comment by mczp** [comment] 2017-06-26 19:45
I think I just hit the same issue, code like this is triggering it:
```
@inject(MCNetRPC, Router)
export class FabricDetails {
  constructor(rpc, router) {
    this.rpc = rpc;
    this.router = router;
    this.loading = true;
    setTimeout(() => { this.load_fabric(); }, 0);
  }

  async load_fabric() {
    console.log(this.router);
    console.log(this.router.currentInstruction);
    //fid = this.router.currentInstruction.params.id;
    //console.log(`Loading fabric details FID: ${fid}`);
  }
}
```
In the console I'm getting:
`Router ...`
`null`

**Comment by ejlaw01** [comment] 2017-07-05 20:49
Is this bug fixed?  I'm having the same issue as @mczp, i.e., this.router returns the full router object but this.router.currentInstruction in the very next line returns null.

**Comment by mchase77** [comment] 2017-07-12 20:27
Seems there is an isActive flag on each route set in router.navigation

**Comment by huochunpeng** [comment] 2018-02-21 05:41
@allencoded, @ejlaw01 can one of you help to test this issue against #571?
Your issue sounds like related to #476 (which is fixed by #571), the events are not published at right point.

However, I could not reproduce your error based on the code from #476. Would appreciate if you guys can test through your code.

Thx.

**Comment by davismj** [comment] 2018-03-21 07:50
@ejlaw01 @mczp can you generate a repro, please?

**Comment by davismj** [comment] 2018-08-03 08:30
Can't rerpo.

**Closed by davismj** 2018-08-03 08:30 UTC
Labels: bug, help wanted

**Comment by jalmansa88** [comment] 2018-08-03 11:00
Having this issue here. 
`Message: Cannot read property 'config' of null`

I've have imported/injected the Router (which config has been defined in app.ts) into my navbar component, and I am not able to get the current route because of null:

`this.router.currentInstruction.config.name`

Help please.
