### ISSUE TITLE
Ensure rejected promise message from activation failure propagates properly

### ISSUE THREAD

**Issue by PWKad** [aurelia/router#36] opened 2015-02-25 21:38 UTC
This enhancement is referenced from Durandal 2.1 issue -  https://github.com/BlueSpire/Durandal/issues/595#issuecomment-76047279

**Comment by devmondo** [comment] 2015-02-26 14:45
!!First!! 
i really like ravendb docs style http://ravendb.net/docs/article-page/3.0/csharp/welcome
good parts
- you can choose a version and docs will reflect that
-the left navigation has collapsible sub topics

**Comment by jdanyow** [comment] 2015-03-08 04:25
dupe of https://github.com/aurelia/router/issues/2

**Comment by EisenbergEffect** [comment] 2015-04-28 19:19
This issue has been addresses via the duplicate.

**Closed by EisenbergEffect** 2015-04-28 19:19 UTC
Labels: duplicate
