### ISSUE TITLE
Default viewModel with child router breaks child routes

### ISSUE THREAD

**Issue by jaimerivera** [aurelia/router#72] opened 2015-04-21 20:04 UTC
This issue happens when the default route for the main router is a view model which has a child router.
When the default view model is loaded the default route on the child router loads.  However, any other routes will not load.  This can be tested by swapping the welcome and child routes in the aurelia-skeleton to set the child routes as the default.  Then clicking on the child route for flikr will load the main route.  If a route is declared in the child router which does not exist in the main router, a route not found exception will occur.

**Comment by bryanrsmith** [comment] 2015-04-25 16:51
This is a slightly different manifestation of #27. The problem is that giving the child a path of `""` gives it an empty path prefix that sort of overlaps with the parent router, so there's no good way to know that the match needs to descend into the child. Maybe we can continue the discussion in #27 to try to reach a good solution.

**Comment by bryanrsmith** [comment] 2015-04-28 03:32
Closing as duplicate of #27.

**Closed by bryanrsmith** 2015-04-28 03:32 UTC
