### ISSUE TITLE
Route Not Found Following Documentation Example

### ISSUE THREAD

**Issue by jrsmith17** [aurelia/router#301] opened 2016-03-06 18:09 UTC
I worked through the documentation on my local windows box, and the site worked as expected. I tried pulling that code onto my remote gentoo box and was immediately slammed with Route Not Found errors. To makes sure it wasn't something from the windows -> linux transition, I restarted the tutorial on my gentoo box. I hit the same error the moment I got to the step including the <router-view></router-view>. Here's the code as I have it.

app.js

```javascript
export class App {
  configureRouter(config, router) {
    config.title = 'Aurelia';
    config.map([
      { 
         route: ['','welcome'], 
         name: 'welcome', 
         moduleId: './welcome', 
         nav: true, 
         title:'Welcome' 
      }
    ]);

    this.router = router;
  }
}
```

app.html

```html
<template>
  <require from="bootstrap/css/bootstrap.css"></require>
  <require from="font-awesome/css/font-awesome.css"></require>

  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">
        <i class="fa fa-home"></i>
        <span>${router.title}</span>
      </a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li repeat.for="row of router.navigation" class="${row.isActive ? 'active' : ''}">
          <a href.bind="row.href">${row.title}</a>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li class="loader" if.bind="router.isNavigating">
          <i class="fa fa-spinner fa-spin fa-2x"></i>
        </li>
      </ul>
    </div>
  </nav>

  <div class="page-host">
    <router-view></router-view>
  </div>
</template>
```

And lastly, here is my error. I also want to note that it's rather unhelpful when the debug console doesn't tell you where in your own code the error was triggered. 

```
ERROR [app-router] Error: Route not found: /
    at AppRouter._createNavigationInstruction (http://192.158.12.240/jspm_packages/npm/aurelia-router@1.0.0-beta.1.1.1/aurelia-router.js:995:29)
    at AppRouter.loadUrl (http://192.158.12.240/jspm_packages/npm/aurelia-router@1.0.0-beta.1.1.1/aurelia-router.js:1476:19)
    at BrowserHistory._loadUrl (http://192.158.12.240/jspm_packages/npm/aurelia-history-browser@1.0.0-beta.1.1.2/aurelia-history-browser.js:281:55)
    at BrowserHistory.activate (http://192.158.12.240/jspm_packages/npm/aurelia-history-browser@1.0.0-beta.1.1.2/aurelia-history-browser.js:185:21)
    at AppRouter.activate (http://192.158.12.240/jspm_packages/npm/aurelia-router@1.0.0-beta.1.1.1/aurelia-router.js:1531:20)
    at http://192.158.12.240/jspm_packages/npm/aurelia-router@1.0.0-beta.1.1.1/aurelia-router.js:1512:20
    at AppRouter.registerViewPort (http://192.158.12.240/jspm_packages/npm/aurelia-router@1.0.0-beta.1.1.1/aurelia-router.js:1514:11)
    at new RouterView (http://192.158.12.240/jspm_packages/npm/aurelia-templating-router@1.0.0-beta.1.1.1/router-view.js:69:19)
    at Object.invoke (http://192.158.12.240/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.1.3/aurelia-dependency-injection.js:359:14)
    at InvocationHandler.invoke (http://192.158.12.240/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.1.3/aurelia-dependency-injection.js:309:168)
error	@	aurelia-logging-console.js:62
log	@	aurelia-logging.js:36
error	@	aurelia-logging.js:69
(anonymous function)	@	aurelia-router.js:1479
g	@	shim.min.js:2220
(anonymous function)	@	shim.min.js:2225
e	@	shim.min.js:2468
```

And in case it's helpful in recreating, here's what "uname -a" returns on my linux box.

```
Linux gentoo-x64 4.0.5-gentoo #1 SMP Sun Oct 4 03:57:27 2015 x86_64 Intel(R) Xeon(R) CPU L5520 @ 2.27GHz GenuineIntel GNU/Linux
```

Edit: It occurred to me to include that I'm running this off an nginx server. I was also able to get the site to show up right after unpacking the zip file.

**Comment by jrsmith17** [comment] 2016-03-07 01:22
I did some stepping through my two setups with the debugger. I can see what's happening, but still haven't wrapped my head around the why. I have my initial breakpoint set at Router.prototype._createNavigationInstruction (aurelia-router.js on line 945). 

Both boxes follow the same path until they arrive at recognizeChar (aurelia-route-recognizer.js at line 454). Inside of the for loop there is the following difference.

Working
```
function recognizeChar(states, ch) {
    var nextStates = []; (( nextStates = [] ))

    for (var i = 0, l = states.length; i < l; i++) { (( i = 0, l = 1, states = [State] ))
      var state = states[i]; ((state = State {charSpec: undefine, nextStates: Array[1]} ))
      nextStates.push.apply(nextStates, state.match(ch));
    }

    return nextStates;
  }
```

Not Working
```
function recognizeChar(states, ch) {
    var nextStates = []; (( nextStates = [] ))

    for (var i = 0, l = states.length; i < l; i++) { (( i = 0, l = 1, states = [State] ))
      var state = states[i];  ((state = State {charSpec: undefine, nextStates: Array[0]} ))
      nextStates.push.apply(nextStates, state.match(ch));
    }

    return nextStates;
  }
```

I would have thought nothing of the off by one array error, but I got to the match function (aurelia-route-recognizer.js at line 58) where nextStates is set to [State] in the working code but still an empty array in the non working code.

My guess is that nextStates is being populated properly, but hopefully someone more familiar with the codebase can point me in the right direction.

**Comment by johnmanko** [comment] 2016-03-07 11:18
I'm confirm this is happening with me, too.

```
$ jspm inspect
     Installed Versions

                    github:Leaflet/Leaflet 0.7.7
                  github:components/jquery 2.2.1
                       github:github/fetch 0.10.1
               github:jspm/nodelibs-assert 0.1.0
                   github:jspm/nodelibs-fs 0.1.2
                 github:jspm/nodelibs-path 0.1.0
              github:jspm/nodelibs-process 0.1.2
                 github:jspm/nodelibs-util 0.1.0
        github:nakupanda/bootstrap3-dialog 1.34.9
       github:steveathon/bootstrap-wysiwyg 1.0.5
                github:systemjs/plugin-css 0.1.20
               github:systemjs/plugin-json 0.1.0
               github:systemjs/plugin-text 0.0.4
                     github:twbs/bootstrap 3.3.6
                                npm:assert 1.3.0
                  npm:aurelia-animator-css 1.0.0-beta.1.1.2
                       npm:aurelia-binding 1.0.0-beta.1.2.2
                  npm:aurelia-bootstrapper 1.0.0-beta.1.1.4
          npm:aurelia-dependency-injection 1.0.0-beta.1.1.5
              npm:aurelia-event-aggregator 1.0.0-beta.1.1.1
                  npm:aurelia-fetch-client 1.0.0-beta.1.1.1
                     npm:aurelia-framework 1.0.0-beta.1.1.4
                       npm:aurelia-history 1.0.0-beta.1.1.1
               npm:aurelia-history-browser 1.0.0-beta.1.1.4
                        npm:aurelia-loader 1.0.0-beta.1.1.1
                npm:aurelia-loader-default 1.0.0-beta.1.1.3
                       npm:aurelia-logging 1.0.0-beta.1.1.2
               npm:aurelia-logging-console 1.0.0-beta.1.1.4
                      npm:aurelia-metadata 1.0.0-beta.1.1.6
                           npm:aurelia-pal 1.0.0-beta.1.1.1
                   npm:aurelia-pal-browser 1.0.0-beta.1.1.4
                          npm:aurelia-path 1.0.0-beta.1.1.1
                     npm:aurelia-polyfills 1.0.0-beta.1.0.1
              npm:aurelia-route-recognizer 1.0.0-beta.1.1.3
                        npm:aurelia-router 1.0.0-beta.1.1.3
                    npm:aurelia-task-queue 1.0.0-beta.1.1.1
                    npm:aurelia-templating 1.0.0-beta.1.1.4
            npm:aurelia-templating-binding 1.0.0-beta.1.1.2
          npm:aurelia-templating-resources 1.0.0-beta.1.1.3
             npm:aurelia-templating-router 1.0.0-beta.1.1.2
                            npm:babel-core 5.8.35
                         npm:babel-runtime 5.8.35
                  npm:bootstrap-datepicker 1.6.0
                               npm:core-js 1.2.6
                              npm:inherits 2.0.1
                                npm:jquery 2.2.1
                                npm:moment 2.11.2
                       npm:path-browserify 0.0.0
                               npm:process 0.11.2
                                  npm:util 0.10.3
```

**Comment by jrsmith17** [comment] 2016-03-30 19:23
It's been over three weeks and I wanted to circle back and see if anyone has had a chance to look at this ticket. If not, Aurelia is effectively unworkable for me.

**Comment by EisenbergEffect** [comment] 2016-03-30 21:43
@bryanrsmith Can you take a look into this?
@jrsmith17 Can you create a consistently failing unit test that we can use to help us provide a fix?

**Comment by bryanrsmith** [comment] 2016-03-31 04:18
If someone can provide a failing test, or a plunker, or a repo that I can clone to reproduce the problem that'd be great.

**Comment by jrsmith17** [comment] 2016-04-03 01:43
I pushed up the fragment from the documentation that wasn't working to my account [here](https://github.com/jrsmith17/portfolio).

Since it has been a while, I ran through testing it again locally on my windows machine and remotely on my gentoo machine. Now both don't work, which I suspect is better than the alternative. The error message I posted above is still accurate.

**Comment by jrsmith17** [comment] 2016-04-06 03:09
I wanted to follow up and make sure there wasn't any issue in accessing my repo. Thanks!

**Comment by EisenbergEffect** [comment] 2016-07-04 17:03
Is this still an issue? If so, it seems like a difference in whatever browser you are running the code in. We'd need more details so we could set up an environment that matches yours.

**Comment by jrsmith17** [comment] 2016-07-04 17:06
This is still an issue, though I have since switched to a different project. I was using whatever the latest version of Chrome and Firefox were at the time.

**Comment by EisenbergEffect** [comment] 2016-07-04 17:16
So, the problem manifested on both Chrome and Firefox on Linux?

**Comment by jrsmith17** [comment] 2016-07-04 17:17
I was using Chrome and Firefox on my local Windows box to access a quick test site I was running off my Gentoo Linux instance using nginx

**Comment by EisenbergEffect** [comment] 2016-07-04 17:35
Hmmm. The code was running on windows then. Perhaps the server was handling the paths differently when files were requested?

It's hard to know without an exact setup end-to-end. I'm going to close this issue for now since it's not affecting you. If someone else has this come up, we can investigate with them.

**Closed by EisenbergEffect** 2016-07-04 17:35 UTC
Labels: bug
