### ISSUE TITLE
activate(), canActivate() running on each route change for child routers

### ISSUE THREAD

**Issue by BlueHayes** [aurelia/router#112] opened 2015-05-26 20:39 UTC
I have a child router configured (in fact a couple of them proceeding each other). Each time the route is changed within the bottom router, the canActivate() and activate() methods for all parent routers are called - apart from the top level router.

activate() and canActivate() should only be called once until the user navigates away from that router's "namespace". I think this is a bug because the top level router's activate methods don't get called (as expected), only the child router ones.

Thanks

**Comment by jadrake75** [comment] 2015-06-02 13:50
@BlueHayes Does this only occur when you are three levels deep or more in the child navigation?  Issue #114 showed me that for two levels deep it did not show up but as soon as I went three levels deep (with a dynamic route at least) it showed up.  This sounds like a duplicate of #114, but I'd let Bryan rule on that.

**Comment by bryanrsmith** [comment] 2015-06-05 20:01
I do believe #114 is a duplicate of this. I'm going to go ahead and close this one since there's more information and some repro Plunkers in the other thread.

**Closed by bryanrsmith** 2015-06-05 20:01 UTC
Labels: bug
