### ISSUE TITLE
Possible bug in redirecting routes with parameters

### ISSUE THREAD

**Issue by ormasoftchile** [aurelia/router#607] opened 2018-06-28 13:01 UTC
**I'm submitting a bug report**

* **Library Version:**
1.6.1

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x

* **Node Version:**
9.11.1

* **NPM Version:**
6.0.0

* **JSPM OR Webpack AND Version**
JSPM 0.16.32 | webpack 2.1.0-beta.17

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
Up to version 1.5.0 of Aurelia-router I was using this configuration:
```
[
{ route: 'seguridad-seleccionar-usuario-nuevo', redirect: 'seguridad-seleccionar-usuario/true', nav: true, title: 'Nuevo Usuario' },
{ route: 'seguridad-seleccionar-usuario-modificar', redirect: 'seguridad-seleccionar-usuario/false', nav: true, title: 'Modificar Usuario' },
{ name: 'seguridad-seleccionar-usuario', route: 'seguridad-seleccionar-usuario/:nuevo', moduleId: PLATFORM.moduleName('modulos/herramientas/seguridad/seleccionar-usuario/index', 'herramientas'), nav: false, title: 'Modificar Usuario' }
]
```
The idea was that the two first routes redirect to the third with different parameters.

After upgrading to 1.6.1, an exception is thrown indicating that the parameter isn't being passed.

**Expected/desired behavior:**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

**Comment by huochunpeng** [comment] 2018-07-01 06:48
Is it a child route? If so could be a duplicate of #605.

**Comment by ormasoftchile** [comment] 2018-07-01 13:10
They are root level routes. I think it's different from #605 .

**Closed** 2018-07-17 02:51 UTC
Labels: bug
