### ISSUE TITLE
Error: There was no router-view found in the view for submenu.

### ISSUE THREAD

**Issue by mahtavata** [aurelia/router#187] opened 2015-08-19 21:24 UTC
I have a router structure like this:

app 
-> 1.1 router-view (menu) -> 1.1.1 router-view (submenu)
-> 2.1 router-view (views)

app (has 2 router-views)
	top menu is rendered in the first one (1.1) and it contains a one router-view (1.1.1) for the sub menu
	the second one contains router-view (2.1) for the application views

The 'There was no router-view found in the view for submenu' error occurs approx. half of the time when I’m refressing my broswer. It’s complaining that the submenu is lacking router-view. The problem is that the submenu does not have and should not have any router-view. I’m guessing that the submenu router-view (1.1.1)  is not rendered / not recognized at all when the actual submenu is rendered and that is the real cause.

**Comment by bryanrsmith** [comment] 2015-08-23 20:33
@mahtavata Would you be able to provide some sample code or a plunkr that reproduces the error?

**Comment by jeremy-holt** [comment] 2015-09-02 02:52
I think I have exactly the same problem.

I'm having trouble understanding how child routers work.
In the two route configs below, I would like to be able to navigate from `produção/lista (production-list)` to `editar/:id (rawmaterial-arrival-edit)`.
```
<a route-href="route:rawmaterial-arrival-edit, params.bind:{id:item.arrivalId}">${item.lotNumber}</a>
```
However, when I try to do this I get
```
Unhandled promise rejection Error: A route with name 'rawmaterial-arrival-edit, params.bind:{id:item.arrivalId}' could not be found. 
Check that `name: 'rawmaterial-arrival-edit, params.bind:{id:item.arrivalId}'` was specified in the route's config.
```

I guess I have to find some way of moving up the tree to the root of the route and then down to the route I'm looking for. However, I just can't work out how to do this. I've tried using $parent without success.

`app.js`
```
configureRouter(config, router) {
        config.title = "Cornhouse controle de estoques";

        config.addPipelineStep("authorize", AuthorizeStep);

        config.map([
            {route: ["", "home"], moduleId: "home/home", title: "Home", name: "home", nav: true, settings: {icon: 'fa fa-fw fa-home'}},
            {route: "materiaprima", moduleId: "rawmaterial/router", title: "Matéria prima", name: "rawmaterial", nav: true, roles: ["Admin", "Production"]},
            {route: "produção/lista", moduleId: "production/production-list", title: "Produção", name: "production-list", roles: ["Admin", "Production"], nav: true},
            {route: "administração", moduleId: "user-admin/router", title: "Administração", name: "administration", nav: true, roles: ["Admin", "Sales"], settings: {icon: 'fa fa-fw fa-lock'}},
            {route: "login", moduleId: "auth/login", title: "Login", nav: false},
            {route: "logout", moduleId: "auth/logout", title: "Logout", nav: false}
        ]);
    }
```

`rawmaterial/router.js`
```
    configureRouter(config, router) {

        this.router = router;

        config.title = "Matéria prima";

        config.map([
            {route: ["", "materiaprima/lista"], moduleId: "rawmaterial/arrivals-list", title: "Lista dos lotes", name: "rawmaterial-arrivals-list", nav: true, roles: ["Production"]},
            {route: "novo", moduleId: "rawmaterial/arrival-edit", title: "Novo lote", name: "rawmaterial-arrival-new", nav: true, settings: {icon: 'fa fa-fw fa-plus'}},
            {route: "editar/:id", moduleId: "rawmaterial/arrival-edit", title: "Editar matéria prima", name: "rawmaterial-arrival-edit"},
            {route: "secador/em-processo", moduleId: "rawmaterial/drying-inprocess", title: "Secagem", name: "drying-inprocess", nav: true},
            {route: "entra-secador/editar/:arrivalId/:dryingId", moduleId: "rawmaterial/enter-dryer", title: "Editar um secagem", name: "rawmaterial-edit-drying"},
            {route: "entra-secador/novo/:arrivalId", moduleId: "rawmaterial/enter-dryer", title: "Alimenta o secador", name: "rawmaterial-new-drying"}
        ]);
    }
}
```
Since the routes have names, I would have thought that the names are "global" to the router, i.e. you should be able to navigate from *any* route to *any* route.

I'm not sure if this is my lack of understanding of how routing works, or whether this is is just "unexpected behaviour"

**Comment by bryanrsmith** [comment] 2015-10-29 04:39
@jeremy-holt your binding syntax isn't quite right.

`<a route-href="route:rawmaterial-arrival-edit; params.bind:{id:item.arrivalId}">${item.lotNumber}</a>`

@mahtavata I haven't been able to repro this myself, but I'm not sure if I've correctly understood your setup. If you're able to provide a plunker or a repository I could take a look at I'd appreciate it. I'll go ahead and close this for now, but will reopen if you can provide more info.

**Closed by bryanrsmith** 2015-10-29 04:39 UTC
Labels: bug
