### ISSUE TITLE
'watch' route fail in Firefox

### ISSUE THREAD

**Issue by Jule-** [aurelia/router#315] opened 2016-03-29 13:14 UTC
Hi,

I tried to make a page named 'watch' and added it to my router :
`{ route: 'watch', name: 'watch', moduleId: 'watch', nav: true, title: 'Watch' }`

With a simple empty declaration :
`export class Watch { ... }`

And it works in Chrome. Unfortunately when I tried to run this in Firefox I have errors.

You can try this Gist in both browsers to see : https://gist.run/?id=515e1400e6628338a956

Any clue?

**Comment by Jule-** [comment] 2016-03-29 13:24
Error message extracted from Firefox console:
```
ERROR [app-router] TypeError: invalid 'in' operand proto
Trace de la pile :
initialize@http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.0/aurelia-templating.js:3194:7
initialize@http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.0/aurelia-templating.js:2343:7
initialize@http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.0/aurelia-templating.js:2256:9
importViewModelResource/<@http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.0/aurelia-templating.js:2591:9
 aurelia-logging-console.js:62:7
error() aurelia-logging-console.js:62
log() aurelia-logging.js:36
error() aurelia-logging.js:69
processResult() aurelia-router.js:1629
_dequeueInstruction/</<() aurelia-router.js:1582
```

**Comment by Jule-** [comment] 2016-03-29 15:00
Maybe some clue here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/watch

How and why router is trying to redefine `Object.prototype.watch` is another question.

Can someone tell me if this can be considered as an issue or it is a limitation of Firefox and no plan to add workaround? In what case it could be great to add this limitation in the documentation.

**Comment by EisenbergEffect** [comment] 2016-03-29 15:22
I'm unaware of any code that accesses Object.protyype.watch...That's a FF-specific, non-standard api that we haven't ever used.

**Comment by Thanood** [comment] 2016-03-29 16:01
Well, it seems you can't call a route "watch" in Firefox. Then if you change that route to "watchx", the routing works again.

@Jule- showed me a link earlier today from Angular issues where they described the same problem with ngClass and they also had this problem with ui-router: https://github.com/angular-ui/ui-router/issues/511.

Maybe you don't need to use Object.prototype.watch directly to run into this. The Angular fix checks for ```hasOwnProperty```. Aurelia router is using ```Object.assign``` to load routes, as it seems. Maybe that's enough to trigger this issue.

Although I must say that I only found "watch" as values, not properties.

**Comment by EisenbergEffect** [comment] 2016-03-29 16:28
@bryanrsmith Can you look into this?

**Comment by Thanood** [comment] 2016-03-29 17:39
Interesting, ```unwatch``` has the same effects.

**Comment by stoffeastrom** [comment] 2016-03-29 18:35
@EisenbergEffect 

I had to take a quick look and as far as I can understand it the root cause is when invoking dependencies

```javascript
  invoke: function invoke(container, Type) {
    return new Type();
  }
```
The problem is `new Type()` which in this case is doing new on the global `watch` which comes from `ensureViewModel`
```javascript
        context.viewModel = childContainer.viewModel = childContainer.get(viewModelResource.value);
```
since `viewModelResource.value` is the global `watch`

**Comment by stoffeastrom** [comment] 2016-03-29 19:22
Oh I think I found the real root cause :)

```javascript
WebpackLoader.prototype.loadModule = function loadModule(id) {
    var _this2 = this;

    var existing = this.moduleRegistry[id];
    if (existing) {
      return Promise.resolve(existing);
    }
```
this will return the `watch` function and yields in above error.
I just tested creating an global `testing` object to confirm
```javascript
window.testing = {};
Object {  }
window.testing["watch"]
function watch(, )
window.testing["watch"]
function watch(, )
```

**Comment by EisenbergEffect** [comment] 2016-03-29 19:29
Ok, interesting. So, we need a hasOwnProperty check there instead and probably also in the default loader as well. @stoffeastrom Interested in submitting a PR?

**Comment by stoffeastrom** [comment] 2016-03-29 19:43
Same thing in `moduleAnalyzer``
```javascript
resourceModule = this.cache[moduleId];
    if (resourceModule) {
      return resourceModule;
    }
```
Let me see if I can get it up and running.. might be multiple repos involved here

**Comment by stoffeastrom** [comment] 2016-03-29 19:48
```javascript
function register(lookup, name, resource, type) {
  if (!name) {
    return;
  }

  var existing = lookup[name];
  if (existing) {
    if (existing !== resource) {
      throw new Error('Attempted to register ' + type + ' when one with the same name already exists. Name: ' + name + '.');
    }

    return;
  }

  lookup[name] = resource;
}
```
same thing here.. @EisenbergEffect where is this code located?

**Comment by stoffeastrom** [comment] 2016-03-29 19:49
nvm `view-resources.js`

**Comment by stoffeastrom** [comment] 2016-03-29 19:52
So fixes those places seems to get it up and running... :)

**Comment by stoffeastrom** [comment] 2016-03-30 04:48
@EisenbergEffect I've updated the PR's

**Comment by Jule-** [comment] 2016-03-30 09:59
Thank you for the quick investigation and fixes. Waiting for the release!

**Comment by EisenbergEffect** [comment] 2016-07-04 22:21
Fixed some time back. Sorry for not closing this issue earlier!

**Closed by EisenbergEffect** 2016-07-04 22:21 UTC
