### ISSUE TITLE
Discussion: Correct time in the pipeline to construct a ViewModel.

### ISSUE THREAD

**Issue by Zoltu** [aurelia/router#64] opened 2015-04-13 01:21 UTC
From a "principle of least surprise" point of view, I believe that the navigation current pipeline is more confusing than it should be.

**Note:** The current system works.  Someone who already understands it is able to do whatever they want as long as they are careful and remember the pipeline ordering.  This discussion is purely about user expectations and making the API easy to understand and do what the user most expects.

As a user, if I have a view and a view model, my expectation is that the view model will only be created if it is needed.  This is supported by the current API for a view model that contains constructor, canActivate, activate, canDeactivate, deactivate.  Since I know (from other documentation/experience) that VMs are created for every activation, this leads me to believe that the lifecycle for a view goes something like:

1. constructor
1. canActivate
	1. activate
	1. canDeactivate
		1. deactivate

Current
----
I believe the current system looks like this:

1. resolveRoute
1. canDeactivate (old VM)
1. constructor (new VM)
1. authorize
1. modelbind (???)
1. canActivate (new VM)
1. deactivate (old VM)
1. activate (new VM)
1. precommit (???)
1. commit (???)

Proposed
----
I believe a more intuitive flow would be:

1. resolveRoute
1. authorize
1. canDeactivate (old VM)
1. canActivate (new VM)
1. deactivate (old VM)
1. constructor (new VM)
1. activate (new VM)

Reasoning
----
Route resolution comes first because almost every other step requires knowing your destination.

authorize comes next because it is likely to change the route, and as mentioned previously many other steps may depend on knowing what the upcoming route is.  For example, canDeactivate may return different results depending on what the next route is.  Maybe you can navigate away from A to B but you can't navigate away from A to C.

canDeactivate and canActivate are called back to back because they are effectively guard clauses on the pipeline.  If either returns false, no more work should be done and many of the other steps don't make sense.  What does it mean to construct a view that is never activated?  What if my view construction is expensive (blocks on server round-trip)?  As a user, my expectations are that construction will occur when the view is actually needed, not before it is needed.

deactivate comes next because at this point we have asserted that we *are* navigating.  It is possible that an error could occur but I believe being redirected to an error page is more appropriate at this point than staying on the current page and having the button appear to do nothing (from a user's point of view).

constructor is next because again, at this point we have asserted that we are moving on to the next page and it is time to get the view model all setup.

activate comes next because it is really a second constructor.  In this proposed model I actually see little benefit to having activate and constructor.  Seems like you could get rid of activate in preference for a well established pattern (construction).

Difficulties
----
There are of course some technical difficulties here.  The primary one that @EisenbergEffect brought up to me earlier is that `canActivate` is a member of the VM which means the VM must be constructed first.  I believe this is a mistake for the reasons mentioned above.  I would much prefer to see a decorator like 
```js
@canActivateClass(MyViewCanActivateChecker)
export class MyView { }
```

This model allows users to check for activatability of their class before the class is constructed.  This keeps the semantics of what a constructor does and when it is called in line with traditional OO patterns.  The disadvantage here is if your `canActivate` does some expensive work that you don't want to have to repeat.  Perhaps `canActivate` returns an object that will be dependency injected into the `constructor` or falsy otherwise?

The other problem is the behavior when the constructor fails.  By the time the constructor fails, you have already deactivated the previous page so now you are in a state where you can't load the next page.  Currently, if `activate` fails the user has a constructed but not-activated VM.  This implies that unless activation occurs before deactivation, there needs to be a way to redirect the user to an error page when there is a failure between deactivate and activate.  The above proposed change would only increase the number of methods that could (constructor and activate) result in such an error page being hit.

**Comment by jonaskello** [comment] 2015-04-17 16:22
I think this is an interesting discussion. I was also confused about the order things run in, but I think better docs would solve a lot. (I am not using Aurelia actively at this time since my current main project is done in Dart. But I am implementing our own Router in Dart that emulates Aurelia's so it will be easier to switch to ES6/Aurelia at some point in the future if we want).

I don't think using the constructor instead of Activate is a good idea because as I understand it the VM is fetched from the DI container which means that if it is registered as singleton it will have it's constructor run once but can potentially be activated multiple times. So constructor as substitute for Activate would not work.

One reason for not wanting to call canActivate() on the actual VM would be that you don't want to run the constructor on the VM unnecessarily. However, following "best practice", you should never do anything expensive in a constructor so this is not really a problem?

**Comment by Zoltu** [comment] 2015-04-17 17:47
Hmm, I wasn't aware that you could re-use a VM, I assumed that they were always freshly constructed.  This definitely throws a wrench in what I was going for.

Personally, I really dislike having objects that can be in an invalid state, such as constructed before authenticating or being re-used after deactivation.  I prefer my objects to either be in a fully valid state or not exist.  My intent was to have this enforced by the pipeline by not constructing the VM until it was reasonable to do so.  In particular, after the authorize step and after deactivation of the previous VM.  However, if the VM can be re-used then this means I have to accept situations where my VM is created at some previous point in time when it was reasonable and then re-used later when perhaps it is no longer in a reasonable state.  I find this very unfortunate.  :(

What happens if you construct a VM with a context-sensitive dependency and then re-use that VM in a different context?  I assume it will be using the dependency from the other context and therefore be in a very hard-to-debug state?  Will Aurelia throw an appropriate error if you try to DI a context-sensitive dependency into a static lifetime object (singleton)?

**Comment by EisenbergEffect** [comment] 2015-04-17 17:59
@Zoltu You misunderstand VM re-use. Re-use happens when a route change occurs that matches the existing module but with different input parameters. There is no invalid state. It just gets pushed through the navigation lifecycle. So, first it is deactivated and if that is successful, it is re-activated with the new data. This is a HUGE deal when it comes to performance.

These instances aren't cached by the DI. They are managed by the routing system for efficiency. You can also take control of this behavior by implementing a special callback `determineActivationStrategy` and returning one of the three constants: `NO_CHANGE`, `INVOKE_LIFECYCLE` or `REPLACE`.

The main problem with the approach outlined above is that it won't work with hierarchies of routers. In order to run the full navigation lifecycle, the entire hierarchy must have it's canActivate run before routing can precede. In order to know if there are child components with this callback, we have to actually instantiate the classes to determine if they have routers that map to child modules.

Bear in mind, there's a pluggable pipeline. So, you can change all of this for your personal use. That's why it was designed that way.

**Comment by Zoltu** [comment] 2015-04-17 18:16
@EisenbergEffect What happens to the injected router in that case?  When I use the DI system to inject a router into my VM, and then a route change occurs that results in the same VM, if the constructor isn't re-run doesn't that mean that my dependency injected router is the one from the original route, not the one from the current route?  Or do both routes have the same router and the router just contains information about the current route (whatever that might be).

**Comment by Zoltu** [comment] 2015-04-17 18:33
It sounds like I need to rethink how I was planning on using VMs.  Given the scenario described by @EisenbergEffect, the VM can be re-used to display different data.  If I understand correctly, if I navigate to `/user?name=Bob` and then from there I navigate to `/user?name=Jane`, the VM would be re-used and therefore the constructor will not be called again.  I will receive a new activate however which is where I should do all of my construction work.

This also means that I need to be very careful about deactivate calls ensuring that the object is cleared out.  In this example, maybe I am showing a user profile.  When Bob is deactivated, my deactivate method *must* clear out any properties it set because otherwise they will be applied to Jane's profile (unless Jane's activate makes sure to clear them out).

This manual object management unfortunately reminds me of C++ destructors.  I was hoping to be able to leverage object construction/destruction to ensure that when I navigated from Bob to Jane, none of Bob's information leaked onto Jane's page.

I believe I can come up with a pattern to work around this, such as delegating to a child object that is always replaced on activate.  Then my data all lies within a single object rather than strewn about the VM.  This does complicate VM binding since binding to getters is not currently as easy as binding to properties, but it is doable.

Another other option is to have my views implement determineActivationStrategy and return `INVOKE_LIFECYCLE` (I presume) to ensure that I get a new VM every time.

Given this information, I believe it is still valuable to have a well defined point in the pipeline when construction occurs and I still believe the most correct point is after routing is complete, in order to avoid constructing something that will never show up.

____

In order to do routing before construction though, `canActivate` would need to be separated out from the VM itself.  As I I mentioned in the original post, `canActivate` can be (optionally) moved to a sister class rather than the VM.  This would allow for a more intuitive pipeline when using the sister-class `canActivate` pattern.  There is still the problem of VM re-use, but it sounds like in this case the navigation pipeline is short-circuited anyway.

**Comment by EisenbergEffect** [comment] 2015-04-17 19:46
@Zoltu You would use `REPLACE` to tell the router that your entire VM should be replaced with a new instance.

Also, again, we can't not instantiate the view model because then we won't know if there's a child router or not. That child router could map to a view model that has a canActivate which should be accounted for in the navigation.

**Comment by jonaskello** [comment] 2015-04-17 20:23
@Zoltu I get your point about not being in an invalid state. But I also think that depends on which states you can consider your VM to have. I come from many years of using Caliburn.Micro, and it has a similar life-cyctle only it has both Initialize and Activate. So I am used to considering my VM to be in "uninitialized" state when first constructed. If you think of a VM as a state machine, you can consider "uninitialized" your starting state. Then when a first call comes to Actiavet it moves to "initialized" state. I usually set a flag at this time so when the second call comes to Activate I don't reload things (don't move from initialized state to initialized state, Caliburn.Micro also does this and only calls Initialize once in total but Activate multiple times). If you continue this line of thinking regarding authentication you could consider the VM to have the "unauthenticated" state when first constructed and "authenticated" state when activated. You could also use Deactivate to move back to "uninitialized" state.

**Comment by EisenbergEffect** [comment] 2015-04-28 19:27
Closing this since changing the lifecycle in tis way would not work with child routers.

**Closed by EisenbergEffect** 2015-04-28 19:27 UTC
