### ISSUE TITLE
Repeat.for doesn't rebind when switching routes in a child router

### ISSUE THREAD

**Issue by devteamexpress** [aurelia/router#246] opened 2015-11-11 06:24 UTC
This is based on the latest aurelia version as of 11-10

Here is my child viewmodel

    export class ChildView {
    
    constructor() {
    }

    configureRouter(config, router) {
        config.map([           
            { route: ['','route1'], name: 'route1', moduleId: 'views/configuration/route1/index', nav: true, auth: true, title: 'General'},            
            { route: ['route2','route2'], name: 'route2', moduleId: 'views/configuration/route2/index', nav: true, title: 'Communication'},            
        ]);
        this.router = router;
    }

    activate() {
                    
    }

}

Here is my view

    <template>

    <ul>
        <li repeat.for="item of router.navigation"><a href.bind="item.href">${item.title}</a></li>
    </ul>

    <router-view></router-view>
  
  </section>
     </template>

When i first load the page it works perfectly, if i switch to route2, the repeat.for doesn't rebind leaving me with no links to navigate back and forth.

The same thing happens with any repeat.for , i created a simple string array and this didn't either rebind.

**Comment by bryanrsmith** [comment] 2015-11-13 05:45
@devteamexpress Are you sure you're up to date on all the Aurelia libraries? That routing setup is exactly what we use in the skeleton navigation project, which appears to be working. If you are up to date, would you be able to post a plunker that reproduces the problem? I'm not able to repro myself.

**Comment by xiwc** [comment] 2015-11-13 10:43
i have the same question.

parent router change, the child router will not refresh bind.

my config:

      "aurelia-binding": "github:aurelia/binding@^0.10.0",
      "aurelia-bootstrapper": "github:aurelia/bootstrapper@^0.18.0",
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@^0.11.0",
      "aurelia-event-aggregator": "github:aurelia/event-aggregator@^0.9.0",
      "aurelia-framework": "github:aurelia/framework@^0.17.0",
      "aurelia-history": "github:aurelia/history@^0.8.0",
      "aurelia-history-browser": "github:aurelia/history-browser@^0.9.0",
      "aurelia-i18next": "github:aurelia/i18n@^0.2.6",
      "aurelia-loader": "github:aurelia/loader@^0.10.0",
      "aurelia-loader-default": "github:aurelia/loader-default@^0.11.0",
      "aurelia-logging": "github:aurelia/logging@^0.8.0",
      "aurelia-metadata": "github:aurelia/metadata@^0.9.0",
      "aurelia-pal": "github:aurelia/pal@^0.2.0",
      "aurelia-pal-browser": "github:aurelia/pal-browser@^0.2.0",
      "aurelia-path": "github:aurelia/path@^0.10.0",
      "aurelia-route-recognizer": "github:aurelia/route-recognizer@^0.8.0",
      "aurelia-router": "github:aurelia/router@^0.13.0",
      "aurelia-task-queue": "github:aurelia/task-queue@^0.8.0",
      "aurelia-templating": "github:aurelia/templating@^0.16.0",
      "aurelia-templating-binding": "github:aurelia/templating-binding@^0.16.0",
      "aurelia-templating-resources": "github:aurelia/templating-resources@^0.16.1",
      "aurelia-templating-router": "github:aurelia/templating-router@^0.17.0",

**Comment by devteamexpress** [comment] 2015-11-13 11:38
Here is my config

    "aurelia-animator-css": "github:aurelia/animator-css@0.18.0",
    "aurelia-binding": "github:aurelia/binding@0.11.3",
    "aurelia-bootstrapper": "github:aurelia/bootstrapper@0.19.0",
    "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.12.1",
    "aurelia-dialog": "github:aurelia/dialog@0.4.4",
    "aurelia-event-aggregator": "github:aurelia/event-aggregator@0.10.0",
    "aurelia-fetch-client": "github:aurelia/fetch-client@0.4.0",
    "aurelia-framework": "github:aurelia/framework@0.18.0",
    "aurelia-history": "github:aurelia/history@0.9.0",
    "aurelia-history-browser": "github:aurelia/history-browser@0.10.0",
    "aurelia-loader": "github:aurelia/loader@0.11.0",
    "aurelia-loader-default": "github:aurelia/loader-default@0.12.0",
    "aurelia-logging": "github:aurelia/logging@0.9.0",
    "aurelia-metadata": "github:aurelia/metadata@0.10.1",
    "aurelia-pal": "github:aurelia/pal@0.3.0",
    "aurelia-pal-browser": "github:aurelia/pal-browser@0.3.0",
    "aurelia-path": "github:aurelia/path@0.11.0",
    "aurelia-route-recognizer": "github:aurelia/route-recognizer@0.9.0",
    "aurelia-router": "github:aurelia/router@0.14.0",
    "aurelia-task-queue": "github:aurelia/task-queue@0.9.0",
    "aurelia-templating": "github:aurelia/templating@0.17.4",
    "aurelia-templating-binding": "github:aurelia/templating-binding@0.17.0",
    "aurelia-templating-resources": "github:aurelia/templating-resources@0.17.3",
    "aurelia-templating-router": "github:aurelia/templating-router@0.18.0",

**Comment by nomack84** [comment] 2015-11-13 12:41
You have to check the forks, they have been causing a lot of troubles.

**Comment by nomack84** [comment] 2015-11-13 12:42
Try this: `jspm inspect --forks`

**Comment by devteamexpress** [comment] 2015-11-13 14:23
Installed Forks
    npm:core-js 0.9.18 1.2.6
    To inspect individual package constraints, use jspm inspect registry:name.

**Comment by xiwc** [comment] 2015-11-14 02:36
# The second level router's :id will not be refreshed after the first level router changed.

### My first level router:

    // 配置路由
    configureRouter(config, router) {

        config.map([{
            route: ['my'],
            name: 'my',
            moduleId: 'my/my-pane',
            nav: true,
            title: '我的'
        }, {
            route: ['project/:id'],
            name: 'project',
            moduleId: 'project/project-pane',
            href: 'project',
            nav: true,
            title: '项目'
        }, {
            route: ['default', ''],
            name: 'default',
            moduleId: 'comp/default/default-pane',
            nav: false,
            title: '默认'
        }, {
            route: ['info'],
            name: 'info',
            moduleId: 'info/info-pane',
            nav: false,
            title: '消息'
        }, {
            route: ['test'],
            name: 'test',
            moduleId: 'test/test-pane',
            href: 'test',
            nav: true,
            title: '测试'
        }]);

        this.router = router;

    }

### My second level router:
    // 配置路由
    configureRouter(config, router) {

        config.map([{
            route: ['dynamic-pane', ''],
            name: 'dynamic-pane',
            moduleId: 'project/dynamic/dynamic-pane',
            nav: true,
            icon: 'volume up',
            title: '项目动态'
        }, {
            route: ['task-pane'],
            name: 'task-pane',
            moduleId: 'project/task/task-pane',
            nav: true,
            icon: 'trello',
            title: '任务面板'
        }, {
            route: ['calendar-pane'],
            name: 'calendar-pane',
            moduleId: 'project/calendar/calendar-pane',
            nav: true,
            icon: 'calendar',
            title: '项目日历'
        }, {
            route: ['resource-pane'],
            name: 'resource-pane',
            moduleId: 'project/resource/resource-pane',
            nav: true,
            icon: 'cloud',
            title: '项目资源'
        }, {
            route: ['resource-router'],
            name: 'resource-router',
            moduleId: 'my/resource/resource-router',
            nav: false,
            icon: 'cloud',
            title: '项目资源'
        }, {
            route: ['news'],
            name: 'news',
            moduleId: 'my/news/news-pane',
            nav: false,
            title: '消息中心'
        }, {
            route: ['settings'],
            name: 'settings',
            moduleId: 'my/settings/settings-pane',
            nav: false,
            title: '用户设置'
        }]);

        this.router = router;
    }

**Comment by xiwc** [comment] 2015-11-15 14:27
# I also test at aurelia-skeleton-navigation-v0.20.0

### my parent router
![image](https://cloud.githubusercontent.com/assets/8816203/11169088/e2466cde-8be6-11e5-9812-c398acd8504a.png)
### my child routers
![image](https://cloud.githubusercontent.com/assets/8816203/11169090/ef873cca-8be6-11e5-94d6-104626784d1f.png)
### the result screenshot
![image](https://cloud.githubusercontent.com/assets/8816203/11169104/cd40aae2-8be7-11e5-8216-8e7c7f648ffd.png)

**Comment by bryanrsmith** [comment] 2015-11-15 20:40
@EisenbergEffect I've confirmed that the router's baseUrl and navigation models are being updated properly, but the binding is not being updated. Could this be related to recent templating changes? If you use `activationStrategy.replace` the view behaves as expected, presumably because that causes a new binding to be created.

**Comment by EisenbergEffect** [comment] 2015-11-15 20:57
@xiwc Can you run a `jspm update` and try it out again. We had some more fixes to binding and templating. Not sure if it solves your issues, but would like you to check.

**Comment by xiwc** [comment] 2015-11-16 03:20
@EisenbergEffect & @bryanrsmith 
 I have checked again with `jspm update`, the issue still there.
My validate branch code: https://github.com/xiwc/aurelia.skeleton.v0.19.test/tree/aurelia-framework-v18

**Comment by xiwc** [comment] 2015-11-16 03:23
FYI: 
![image](https://cloud.githubusercontent.com/assets/8816203/11173691/8317043a-8c54-11e5-9915-99859ba9aaca.png)

**Comment by bryanrsmith** [comment] 2015-11-16 04:55
Yep, I still repro on newest releases as well.

**Comment by xiwc** [comment] 2015-12-02 03:03
is there some fixing solution.

**Comment by devteamexpress** [comment] 2015-12-18 06:43
Can we get an update on this? This bug is really killing our company's app.

**Comment by xiwc** [comment] 2015-12-18 13:22
i use following way to fix:
```
   activate(params, routeConfig, navigationInstruction) {

        this.router.parent.currentInstruction = navigationInstruction;

        // fix bug for second router's navigation href not refresh when parent router changed.
        var nav = this.router.navigation;
        _.each(this.router.navigation, (current) => {
            current.href = '';
        });

        this.router.refreshBaseUrl();
        this.router.refreshNavigation();

    }
```

**Comment by EisenbergEffect** [comment] 2015-12-18 19:52
I will personally look into it next week.

**Comment by mikefills** [comment] 2015-12-19 19:14
I hate I have to ask this, more than 1 month and no solution to the issue?
I'm looking into choosing Aurelia for a very soon project but this kind of bugs are scary.
Again, I don't want to sound harsh, I know team has been working on many things...

**Comment by EisenbergEffect** [comment] 2015-12-21 21:45
@bryanrsmith I've discovered the issue.

See: https://github.com/aurelia/router/blob/master/src/router.js#L326 

There's a check whereby the href is not updated if it already exists. This creates the problem because the navModel and its href are pre-existing. This check was put in place so as to not over-write an explicit href provided by the developer.

I believe this should be fixable by adding a special private property to the navModel which indicates that the href was explicitly provided and then checking that property instead of the href itself.

@bryanrsmith Do you think you can get to this soon?

**Comment by bryanrsmith** [comment] 2015-12-22 01:00
I'll try. Sounds like a great first PR if anyone is interested in contributing :-)

**Comment by xiwc** [comment] 2016-02-22 02:29
# Suggesting fixing solution
![image](https://cloud.githubusercontent.com/assets/8816203/13207941/1623a2e6-d94f-11e5-968c-5555933662df.png)

**Comment by EisenbergEffect** [comment] 2016-05-16 14:51
Does anyone want to submit a PR is or this issue no longer important?

**Comment by devmai** [comment] 2016-05-18 18:29
This is the most commented issue as bug in aurelia router and still open since November. All recommodated fixes never worked for me. It's still very important because it prevents more advance leveled SPAs. What think the others?

**Comment by EisenbergEffect** [comment] 2016-05-18 18:45
Why don't you submit a PR with the fix? It would be a great contribution. We marked this as "help wanted" because we think it's a good fit for someone from the community to get their feet wet contributing.

**Comment by yaredtek** [comment] 2016-05-19 20:19
is this issue fixed?

**Comment by EisenbergEffect** [comment] 2016-05-19 20:42
No it's not fixed. We are asking for a community member to make the PR. It should be easy.

**Comment by simonfox** [comment] 2016-05-25 19:56
I'm going to have a crack at fixing this today

**Comment by simonfox** [comment] 2016-05-27 19:46
@EisenbergEffect @bryanrsmith any chance my PR can get looked at before next weeks release cycle? I have some time over the weekend if any changes to it are required and would be great to get it merged before next week.

**Comment by EisenbergEffect** [comment] 2016-05-28 02:01
Mostly likely it will get in. @bryanrsmith Can you take a look? It seems pretty straghtforward to me.

**Closed** 2016-05-30 20:37 UTC
Labels: bug, help wanted
