### ISSUE TITLE
addRoute throws config error when list of routes provided

### ISSUE THREAD

**Issue by jfstephe** [aurelia/router#509] opened 2017-08-03 11:29 UTC
**I'm submitting a bug report**

* **Library Version:**
1.1.0

* **Operating System:**
Linux Ubuntu (docker)

* **Node Version:**
v8.1.3

* **NPM Version:**
5.0.3

* **JSPM OR Webpack AND Version**
JSPM 0.16.53

* **Browser:**
Chrome

* **Language:**
Typescript

**Current behavior:**
Add a route using the following

```
    this.router.addRoute({
        route: ['routeA', 'routeB'],
        name: 'blah', moduleId: './pages/dashboard/Dashboard',
        nav: true, title: 'My title'
    });

```

Results in:

```
aurelia-router.js:1107 Uncaught Error: Invalid Route Config for "blah": You must specify a "route:" pattern.
    at validateRouteConfig (aurelia-router.js:1107)
    at AppRouter.addRoute (aurelia-router.js:896)
    at NavBar.execute.NavBar.addBlankDashboard (NavBar.ts:36)
    at CallScope.evaluate (aurelia-binding.js:1583)
    at Listener.callSource (aurelia-binding.js:5146)
    at eval (aurelia-binding.js:5170)
    at HTMLDocument.handleDelegatedEvent (aurelia-binding.js:3291)
```

It seems to be in the validation code but the addRoute function looks to also be expecting a string rather than an array.

**Expected/desired behavior:**
Not to throw an exception and work as the declarative config blocks work.

* **What is the expected behavior?**
addRoute to work like the config specified declaratively.

* **What is the motivation / use case for changing the behavior?**
Seems like it should always have worked like this.

**Comment by Vheissu** [comment] 2017-08-22 06:24
This has been raised before, here specifically: https://github.com/aurelia/router/issues/158 - even though it's an issue from 2015 the answer I believe still stands. @EisenbergEffect might want to weigh in on this, but that is intended behaviour that `addRoute` only allows you to specify a singular route.

**Comment by EisenbergEffect** [comment] 2017-08-22 06:27
Correct.

**Comment by EisenbergEffect** [comment] 2017-08-22 06:28
I'm not sure we can change it at this point. Seems like a breaking change for an scenario that could be handled with another existing API.

**Comment by jfstephe** [comment] 2017-08-22 06:42
Thanks for the other issue reference. The main problem I have with this is the Typescript definition of RouteConfig allows either an item or a list and yet the addRoute() call doesn't allow the list part. This is just asking for confusion/wasted time etc.
If a longer term solution isn't possible for now, can the jsdocs for the addRoute call be updated to include a warning or some such to nudge devs into 'the pit of success'?

**Comment by EisenbergEffect** [comment] 2017-08-22 07:24
Good point. I missed that scenario. Let's take a look at this and see if we can improve the situation.

**Comment by fkleuver** [comment] 2018-02-16 10:05
Stumbled upon this today when looking through the code. It kind of feels like `Router.addRoute` wasn't meant to be a public API, because it makes assumptions on its input based on how `RouterConfiguration.mapRoute` calls it.
That one transforms a RouteConfig with a route array into multiple RouteConfigs and does a few other things. Seems like you really can't "win" by calling addRoute over mapRoute apart from it being less steps.
Regardless, why not just make that transform into a function and have `addRoute` call it when RouteConfig.route is an array? I don't see any breaking changes as long as it doesn't do any of the other things that `mapRoute` does. Only makes the API more predictable..

**Comment by davismj** [comment] 2018-02-19 05:38
@fkleuver I think that's a great approach. PR welcome!

**Comment by fkleuver** [comment] 2018-02-19 09:31
@davismj done! #576

**Comment by davismj** [comment] 2018-03-15 06:52
@fkleuver Merged. Thanks for your hard work! Code looks perfect.

**Closed** 2018-03-15 06:51 UTC
Labels: bug, enhancement
