### ISSUE TITLE
deactivate() does not invoked after navigate to other router module.

### ISSUE THREAD

**Issue by jdanyow** [aurelia/router#411] opened 2016-09-26 12:04 UTC
@xiwc commented on [Fri Aug 19 2016](https://github.com/aurelia/framework/issues/563)

**I'm submitting a bug report**
- **Library Version:**
  "aurelia-framework": "^1.0.0-rc.1.0.0",

**Please tell us about your environment:**
- **Operating System:**
  Windows [7|10]
- **Node Version:**
  v4.4.2
- **NPM Version:**
  3.10.5
- **JSPM OR Webpack AND Version**
  webpack 1.13.1
- **Browser:**
  Chrome 52.0.2743.116 m
- **Language:**
  ESNext

**Current behavior:**
when i switch router.
1. `#/server/disk  -> #/server/other`  deactivate() is invoked normally
2. `#/server/disk -> #/network/other` deactivate() is not invoked normally

---

@guilhermewaess commented on [Tue Sep 13 2016](https://github.com/aurelia/framework/issues/563#issuecomment-246892236)

Are you using layouts?
I have the same problem, but with attached() <- attached() never calls when I using layouts :(

---

@alpox commented on [Wed Sep 14 2016](https://github.com/aurelia/framework/issues/563#issuecomment-246932154)

Seems to be a duplicate of https://github.com/aurelia/templating-router/issues/34

**Comment by mbenedyk** [comment] 2016-12-13 16:03
any progress here?

**Comment by MT-PL-SWF-Dev** [comment] 2017-01-11 17:56
I have made some research and found out that this bug is probably caused by if clauses in "activation.js" file. https://github.com/aurelia/router/blob/master/src/activation.js#L72

```javascript
if (viewPortPlan.childNavigationInstruction) {
      findDeactivatable(viewPortPlan.childNavigationInstruction.plan, callbackName, list);
    } else if (prevComponent) {
      addPreviousDeactivatable(prevComponent, callbackName, list);
}
```

If we navigate across AppRouter from nested Child Router _viewPortPlan.childNavigationInstuction_ is _undefined_ while running _canDeactivate()_ but before _deactivate()_ is called there is called _loadRoute()_ method which sets _viewPortPlan.childNavigationInstuction_
After this _deactivate()_ step kicks in but does not call _addPreviousDeactivatable(prevComponent, callbackName, list);_ but rather search for deactivatable in plan for _childNavigationInstruction_!

In our project it is quite serious scenario which cannot be resolved by decent workarounds.

Possible solution would be removing _else_ keyword, but personally I'm not 100% sure if it is safe way. Can anyone more experienced throw some light on this topic?

**Comment by qraynaud** [comment] 2017-03-20 17:10
Since #464 has landed, this issue should be closed right?

**Comment by MT-PL-SWF-Dev** [comment] 2017-03-20 17:13
I belive yes, however I don't see this change in repository though it has been merged. Strange.

**Comment by qraynaud** [comment] 2017-03-20 17:18
Ok, I just looked and it was backed out here : https://github.com/aurelia/router/commit/8ef8840adff0bb3f7abd83af3843d731974e7ba8

**Comment by MT-PL-SWF-Dev** [comment] 2017-03-20 17:19
Ah seems like this solution wasn't viable after all. Thank you for clarifying.

**Comment by qraynaud** [comment] 2017-03-20 17:20
Yeah, that is sad because both those bugs are pretty annoying sometimes.

**Comment by EisenbergEffect** [comment] 2017-03-21 03:23
The fix that was submitted caused a massive regression so we had to revert it.

**Comment by MT-PL-SWF-Dev** [comment] 2017-03-31 10:14
Sorry to hear that. I had some doubts but I couldn't check it properly. I'll try to figure out something later.

**Comment by istrau2** [comment] 2017-05-02 14:36
I am running into this as well. This is a pretty serious issue (imo) as it can cause some really bad bugs (with memory leaks etc. as observers are usually unsubscribed in deactivate etc.)

**Comment by istrau2** [comment] 2017-05-02 14:41
For those looking for a workaround. In my experience, canDeactivate() seems to get called as you would expect (on child routers even when navigation occurs on the parent). You can just put the logic in canDeactivate instead of deactivate.

**Comment by CD-UNCC** [comment] 2017-05-04 14:45
as of today `deactivate()` is not being called on standard router route changes.

**Comment by m-andrew-albright** [comment] 2017-05-23 15:35
I have begun experiencing this issue today (or probably long ago, but it only exhibits symptoms after a recent change in our code base)

**Comment by m-andrew-albright** [comment] 2017-09-22 18:07
Do we have any idea how soon this fix will trickle down into a release?  This will be huge for my team.

**Comment by davismj** [comment] 2017-10-31 11:53
@m-andrew-albright this is live in 1.4.0 since Oct 2. Thanks for your patience.

**Closed by davismj** 2017-10-31 11:53 UTC
Labels: bug
