### ISSUE TITLE
activate(...) method doesn't return query string/params for default route

### ISSUE THREAD

**Issue by MaluTom** [aurelia/router#40] opened 2015-03-05 18:33 UTC
Placing the following code in the Welcome class for the aurelia-skeleton -
````
 activate(params, queryString, routeConfig){
    console.log(queryString);
  }
```

This results in the following result when using the default route:
http://localhost:9000?var1=bla
Object {}

However, using the URL http://localhost:9000#/?var1=bla
Returns 
Object {var1: "bla"}

**Comment by EisenbergEffect** [comment] 2015-05-09 05:34
@bryanrsmith Assigning this to you to look at after you finish up your current tasks.

**Comment by EisenbergEffect** [comment] 2015-10-12 06:22
@bryanrsmith This has been around for a while. Can you take a look at it?

**Comment by bryanrsmith** [comment] 2015-10-13 05:18
@EisenbergEffect What's the expected behavior? The application is configured to not use pushstate, so I think this is working as intended. There is code to transition from path to hash URLs, but it only kicks in if the application asks for pushstate & the browser doesn't support it.

**Comment by EisenbergEffect** [comment] 2015-10-13 05:20
@bryanrsmith I think you are right. I'm going to close this.

**Closed by EisenbergEffect** 2015-10-13 05:20 UTC
Labels: bug
